### ISSUE TITLE
inconsistency with paper 

### ISSUE THREAD

**Issue by NTOMM** [vazirilab/SID#5]
https://github.com/vazirilab/SID/blob/67c3d35bc04ca2cc37ff29ad16258dc8bcda2f11/sid_main.m#L268

In the paper, the reconstruction is performed on  the std image. However, in the code, the reconstruction is performed on the spatial filter computed from NNMF, and I could not find the place where the std image is used. Could you explain this?

**Comment by nobias** [comment]
Yeah, the SID code has evolved since the acceptance of the manuscript, and we have in the meantime concluded that using NNMF components instead of the stddev image works better in most cases (especially when there are many active neurons in the movie) and allows manual rejection of components that contain background or other undesirable dynamics.
If you still want to use the stddev image for subsequent steps, simply assign it to the `SID_output.S` field as follows:
`SID_output.S = SID_output.std_image(:)';`

P.S.: IMHO it would be nice if you provided a little bit of information about yourself on your github profile (e.g. affiliation, position): I find it a bit odd to deal with entirely anonymous colleagues within the scientific community, and we are of course always curious about who is using our open source code. Thanks!
